"use client";

// import type { Metadata } from "next";
import { Poppins } from "next/font/google";

import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import ClientProvider from "./ClientProvider";
import { usePathname } from "next/navigation";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
//   icons: {
//     icon: "/icon.png",
//   },
// };

const disableNavbar = ["/login", "/register"];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();

  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <ClientProvider>
          {!disableNavbar.includes(pathname) && <Navbar />}
          {children}
        </ClientProvider>
      </body>
    </html>
  );
}
